#BANNER
banner:
  charset: UTF-8
  location: banner.txt

#SERVIDOR
server:
  port : 8090


spring:
  datasource: 
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/curso
    username: postgres
    password: 5432
  jpa: 
    generate-ddl: true
    show-sql: true
    hibernate: 
      ddl-auto: create-drop
